Don't filter out discovered BT peripherals by `isPresent` (Windows)
LLK/scratch-link pull request #128
Opened 2019-05-23 02:34 UTC by evhan55

### Resolves

- Resolves #94: After connecting EV3 on windows, can't reconnect without first un-pairing

### Proposed Changes

Remove the filtering on the `isPresent` property when returning a list of discovered peripherals.

### Reason for Changes

The `isPresent` property is not true for devices that are already paired, since they are cached.
Reference: https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/device-information-properties under "System.Devices.Aep.IsPresent"

2019-05-23 02:36 UTC, evhan55 commented
@cwillisf 

We are looking into issue #94 in preparation for the LEGO Spike which also exhibits this bug in addition to the EV3.  I found that by commenting on the filtering of discovered peripherals based on the `isPresent` property, the bug is fixed.  According to documentation, once BT devices are paired on Windows, they enter a cache and `isPresent` is no longer true for them.  So, I think we don't want to filter on that property? The Windows UWP documentation on this stuff is worded in a confusing way, but commenting on what I did does fix the problematic symptom we are seeing.

2019-05-23 02:48 UTC, evhan55 commented
@cwillisf 

Another possible way to fix this is to check the `isPaired` property and check the following:

- `isPresent`? if not, `isPaired`?

to prevent getting cached devices.

2019-05-23 03:00 UTC, evhan55 commented
It seems the previous fix I mention actually always returns all paired devices whether they are present or not, so I have to rethink the strategy, sorry for the false alarm!

2019-05-23 03:36 UTC, evhan55 commented
Saving this discussion here for reference:
https://social.msdn.microsoft.com/Forums/windowsapps/en-US/899f6b6e-19fd-40c5-ba1c-741b60b6cfd8/getting-devicewatcher-updates-when-ble-device-is-not-reachable?forum=wpdevelop

2019-05-28 16:51 UTC, cwillisf requested changes
I think it needs a comment but the ~code~ looks great!

2019-05-28 16:51 UTC, cwillisf commented on Windows/scratch-link/BTSession.cs
> -                || isPresent == null || (bool)isPresent == false)
I would recommend leaving a comment here to remind us why we don't check `isPresent`... otherwise I can see us reintroducing this bug in a year or two :/

Also, out of curiosity: when a device is paired, is `isPresent` null or is it false?

2019-05-29 11:56 UTC, evhan55 commented on Windows/scratch-link/BTSession.cs
> -                || isPresent == null || (bool)isPresent == false)
@cwillisf 

When the device is paired on Windows10 and I try the following:
```
deviceInformation.Properties.TryGetValue(IsPresentPropertyName, out var ispresent);
Debug.Print("ispresent: {0}", ispresent);
```

It prints:
`ispresent: False`

2019-05-29 12:08 UTC, evhan55 commented
@cwillisf Thanks for the review, I added a comment to try to explain the change.  Please let me know if it's not clear enough and I can try again.

2019-05-31 17:37 UTC, cwillisf approved these changes
The comments are great! Thanks :)

2019-05-31 17:39 UTC, evhan55 commented
@cwillisf Thanks! I found a small typo in the first comment (extra 'for') so I will fix that and then merge.

2019-05-31 17:46 UTC, merged