Feature/advertisementdata
LLK/scratch-link pull request #139
Opened 2019-07-16 18:30 UTC by knandersen

### Resolves

A new version of #120 since the feature has been revised a bit. It resolves #112. 

### Proposed Changes

This pull request allows Scratch Link's BLE Session to accept a filter based on BLE Advertisement Manufacturer Data. This is an optional filter to distinguish different devices that share the same BLE Service and Characteristic UUID.

It assumes the manufacturer data is structured as proposed (although at the time of writing not established) by the Web Bluetooth standard: https://webbluetoothcg.github.io/web-bluetooth/#example-filter-by-manufacturer-service-data

An example of the filter provided by the client (in this case Scratch VM using a LEGO Boost extension):
```
{
  filters: [{
    services: [BoostBLE.service],
      manufacturerData: {
        0x0397: {
          dataPrefix: [0x00, 0x40],
          mask: [0x00, 0xFF]
        }
      }
    }],
  optionalServices: []
}
```

The `dataPrefix` and `mask` will be bitwise AND'ed, and any device discovered by Scratch Link will have it's manufacturer data prefix AND'ed with the supplied mask. The two AND'ed results will be compared, and if they match, Scratch Link will include the device in discovered devices.

`dataPrefix` and `mask` must be the same length, and max 32 bytes.

### Reason for Changes

LEGO products featuring BLE and the LEGO Wireless Protocol 3 and later (https://lego.github.io/lego-ble-wireless-protocol-docs/) will only feature a single BLE service and characteristic with the same UUID shared across multiple products. This means that individual "product" extensions will not be able to scan for individual devices based on UUID alone, but will need to distinguish devices based on the manufacturer data provided in the device's advertisement data.

2019-07-16 18:32 UTC, knandersen commented
Reopening this PR as agreed with the Scratch Team to resolve a bug around connecting to LEGO BOOST Move Hubs, described in https://github.com/LLK/scratch-vm/issues/2230

2019-07-19 20:23 UTC, cwillisf approved these changes
:+1: looks good! Thanks for the quick fix in b3d1080616d0c4be6ef3b5dabeb3bfdf84964c14 :D

2019-07-20 13:38 UTC, knandersen commented
@cwillisf Thanks for the review! Sorry to bother you again, but I gave the code an extra look and thought I could make it a little more safe and robust. Would you mind looking it over again?

2019-07-23 03:12 UTC, cwillisf requested changes
I left a suggestion for a small optimization but overall I do agree that your recent changes are good :)

2019-07-23 03:12 UTC, cwillisf commented on macOS/Sources/scratch-link/BLESession.swift
> +                var mask = [UInt8](Array(repeating:0xFF, count:dataPrefix.count))
It might be better to move this into an `else` clause so that if the caller provides a mask we skip this allocation in that case. I don't remember how (if at all) to do that while defining the `mask` variable, though. Maybe it could be something like:
`let mask = (values["mask"] as? [UInt8] ?? [UInt8](Array(repeating: ... ))`
(sorry, out of practice with my Swift syntax...)

2019-07-23 17:06 UTC, knandersen commented on macOS/Sources/scratch-link/BLESession.swift
> +                var mask = [UInt8](Array(repeating:0xFF, count:dataPrefix.count))
Ah, great, thanks! I didn't know about the `??` nil-coalescing operator, but it's perfect for this scenario.

2019-07-23 17:12 UTC, cwillisf approved these changes
Looks good!

2019-07-23 17:13 UTC, merged